package com.server.asset.entity;
// Generated 04 Jan 14 15:05:08 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * Condition generated by hbm2java
 */
public class Condition  implements java.io.Serializable {


     private int idCondition;
     private String conditionName;
     private Set assets = new HashSet(0);

    public Condition() {
    }

	
    public Condition(int idCondition) {
        this.idCondition = idCondition;
    }
    public Condition(int idCondition, String conditionName, Set assets) {
       this.idCondition = idCondition;
       this.conditionName = conditionName;
       this.assets = assets;
    }
   
    public int getIdCondition() {
        return this.idCondition;
    }
    
    public void setIdCondition(int idCondition) {
        this.idCondition = idCondition;
    }
    public String getConditionName() {
        return this.conditionName;
    }
    
    public void setConditionName(String conditionName) {
        this.conditionName = conditionName;
    }

    @JsonIgnore
    public Set getAssets() {
        return this.assets;
    }

    public void setAssets(Set assets) {
        this.assets = assets;
    }


}


